---
title: "Sinconv"
output: html_document
---

```{r setup, include=FALSE}

#importa csv
#Data da extração dos dados: ?06/03/2018 02:22:03
sinconv <- read.csv("siconv_convenio.csv", sep = ";")
empenhos <- read.csv("siconv_empenho.csv", sep = ";")
propostas <- read.csv("siconv_proposta.csv", sep = ";")
situacao <- read.csv("siconv_historico_situacao.csv", sep = ";")
meta <- read.csv("siconv_meta_crono_fisico.csv", sep = ";")
obtv <- read.csv("siconv_obtv_convenente.csv", sep = ";")

library(RPostgreSQL)
library(tidyverse)
library(rgdal)
source('funcoes-sinconv.R')

drv <- DBI::dbDriver("PostgreSQL")

CONFIG_FILE_PATH = "../config/config.yml"

con1 <- DBI::dbConnect(drv,
                       host = config::get("host", file = CONFIG_FILE_PATH),
                       port = config::get("port", file = CONFIG_FILE_PATH),
                       user = config::get("user", file = CONFIG_FILE_PATH),
                       password = config::get("password", file = CONFIG_FILE_PATH),
                       dbname = config::get("dbname1", file = CONFIG_FILE_PATH)
)

con2 <- DBI::dbConnect(drv,
                       host = config::get("host", file = CONFIG_FILE_PATH),
                       port = config::get("port", file = CONFIG_FILE_PATH),
                       user = config::get("user", file = CONFIG_FILE_PATH),
                       password = config::get("password", file = CONFIG_FILE_PATH),
                       dbname = config::get("dbname2", file = CONFIG_FILE_PATH)
)

convenio.geopb.nao.tratado <- dbGetQuery(con1, "select * from t_convenio")

convenio.geopb <- convenio.geopb.nao.tratado %>%
    filter(
        str_detect(numero_convenio, "^[0-9]{6}/") |
        nchar(numero_convenio) == 6
    ) %>%
    mutate(
        numero_convenio = ifelse(nchar(numero_convenio) > 6, substr(numero_convenio, 1, 6), numero_convenio)
    )

#filter(grep('^([0-9]{6}/)', numero_convenio))

obra.geopb <- dbGetQuery(con1, "select * from t_obra")

ids_conhecidos_geopb <- convenio.geopb$numero_convenio

obra.convenio.geopb <- obra.geopb %>% 
    left_join(convenio.geopb, by = c("id" = "fk_obra")) %>%
    filter(!is.na(numero_convenio) & nchar(numero_convenio) == 6)

dbDisconnect(con1)
dbDisconnect(con2)

```


```{r}

#importa csv

propostasPb <- propostas %>% 
    filter(UF_PROPONENTE == "PB") %>% 
    filter(ANO_PROP >= "2013") 


propostasPbSinconv <- propostasPb %>% 
    left_join(sinconv, by = "ID_PROPOSTA") 

propostasPbTratada <- propostasPbSinconv %>% 
    filter(SIT_CONVENIO %in% c("Em execução", "Prestação de Contas em Análise", "Prestação de Contas Aprovada", "Prestação de Contas enviada para Análise",
                               " Prestação de Contas Aprovada com Ressalvas", "Prestação de Contas Iniciada Por Antecipação",
                               "Prestação de Contas em Complementação", "Prestação de Contas Rejeitada"))

join.geopb.propostas <- obra.convenio.geopb %>% 
    left_join(propostasPbTratada %>% mutate(NR_CONVENIO = as.character(NR_CONVENIO)), by = c('numero_convenio' = 'NR_CONVENIO'))
```


```{r}

consolida.convenios <- consolida_convenios("/home/lucasd/Desktop/obras-pb/analysis/dados-sinconv") %>% 
    filter(UF_PROPONENTE == "PB") %>%
    filter(ANO >= 2013) %>% 
    filter(SIT_CONVENIO %in% c("Em execução", "Prestação de Contas em Análise", "Prestação de Contas Aprovada", "Prestação de Contas enviada para Análise",
                               " Prestação de Contas Aprovada com Ressalvas", "Prestação de Contas Iniciada Por Antecipação",
                               "Prestação de Contas em Complementação", "Prestação de Contas Rejeitada"))

join.geopb.consolida.convenios <- obra.convenio.geopb %>% 
    left_join(consolida.convenios %>% mutate(NR_CONVENIO = as.character(NR_CONVENIO)), by = c('numero_convenio' = 'NR_CONVENIO'))
```


```{r}

carrega.limpa.historicos <- carrega_e_limpa_historicos("/home/lucasd/Desktop/obras-pb/analysis/dados-sinconv", ids_conhecidos_geopb)


join.geopb.historico <- obra.convenio.geopb %>% 
    left_join(carrega.limpa.historicos %>% mutate(NR_CONVENIO = as.character(NR_CONVENIO)), by = c('numero_convenio' = 'NR_CONVENIO'))
```


```{r setup, include=FALSE}

join.geopb.empenhos <- obra.convenio.geopb %>% 
    left_join(empenhos %>% mutate(NR_CONVENIO = as.character(NR_CONVENIO)), by = c('numero_convenio' = 'NR_CONVENIO'))

```


Tenta criar heurística pra fazer join dos dados do geopb com o sinconv através da descrição da obra presente em cada sistema.

```{r}
filtraArtigos <- function(lista){
    result = c()
    for(palavra in lista){
        if(nchar(palavra) > 3){
             result = c(result, palavra)
        }
    }
    return(result)
}


dados_sinconv_cg <- propostasPbTratada %>% filter(MUNIC_PROPONENTE == 'CAMPINA GRANDE')
dados_geopb_cg <- obras.2013 %>% filter(nome.x == 'Campina Grande')

cross_join_sinconv_geopb <- merge(dados_sinconv_cg, dados_geopb_cg, all=T)

cross_join_sinconv_geopb <- cross_join_sinconv_geopb %>% 
    mutate(OBJETO_PROPOSTA = as.character(OBJETO_PROPOSTA)) %>% 
    group_by(id.y)

cross_join_sinconv_geopb <- cross_join_sinconv_geopb %>% 
    mutate(OBJETO_PROPOSTA = tolower(OBJETO_PROPOSTA), descricao_sucinta_obra = tolower(descricao_sucinta_obra))

cross_join_sinconv_geopb <- cross_join_sinconv_geopb %>% 
    mutate(palavras_iguais = length(intersect(filtraArtigos(unlist(strsplit(OBJETO_PROPOSTA, " "))), filtraArtigos(unlist(strsplit(descricao_sucinta_obra, " "))))))

View(cross_join_sinconv_geopb %>% select(OBJETO_PROPOSTA, descricao_sucinta_obra, palavras_iguais))
```






